biznes/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace biznes.Controllers
{
    public class DocumentsController : Controller
    {
        // GET: Documents
        public ActionResult Index()
        {
            return RedirectToAction("Codex");
        }

        public ActionResult Codex()
        {
            return View();
        }

        public ActionResult Lex()
        {
            return View();
        }

        public ActionResult Resolutions()
        {
            return View();
        }
    }
}

biznes/Controllers/EvaluationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace biznes.Controllers
{
    public class EvaluationsController : Controller
    {
        // GET: Evaluations
        public ActionResult Index()
        {
            return RedirectToAction("EstimationLand");
        }

        public ActionResult EstimationLand()
        {
            return View();
        }

        public ActionResult PropertyValuation()
        {
            return View();
        }

        public ActionResult EvaluationEquipment()
        {
            return View();
        }

        public ActionResult EvaluationCars()
        {
            return View();
        }
    }
}

biznes/Controllers/GeodeticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace biznes.Controllers
{
    public class GeodeticsController : Controller
    {
        // GET: Geodetics
        public ActionResult Index()
        {
            return RedirectToAction("CaptureM");
        }

        public ActionResult CaptureM()
        {
            return View();
        }

        public ActionResult ExecutiveShooting()
        {
            return View();
        }

        public ActionResult GeideticsWorks()
        {
            return View();
        }

        public ActionResult TransferToNature()
        {
            return View();
        }
    }
}

biznes/Controllers/LandManagementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace biznes.Controllers
{
    public class LandManagementsController : Controller
    {
        // GET: LandManagements
        public ActionResult Index()
        {
            return RedirectToAction("SectionUnion");
        }

        public ActionResult SectionUnion()
        {
            return View();
        }

        public ActionResult AllocationLand()
        {
            return View();
        }

        public ActionResult PreparationDocumentationLandPlot()
        {
            return View();
        }

        public ActionResult PreparationDocumentationLandPrivatization()
        {
            return View();
        }

        public ActionResult AppointmenCadastralNumber()
        {
            return View();
        }
       
    }
}

biznes/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace biznes.Controllers
{
    public class ServicesController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Geodetic");
        }

        public ActionResult LandManagement()
        {
            return View();
        }

        public ActionResult Geodetic()
        {
            return View();
        }

        public ActionResult Evaluation()
        {
            return View();
        }

    }
}

biznes/Views/LandManagements/AllocationLand.cshtml
@{
    ViewBag.Title = "Разработка проекта отвода земельного участка";
}

<style>
    .sidebar-nav {
        padding: 9px 0;
    }

    .dropdown-menu .sub-menu {
        left: 100%;
        position: absolute;
        top: 0;
        visibility: hidden;
        margin-top: -1px;
    }

    .dropdown-menu li:hover .sub-menu {
        visibility: visible;
    }

    .dropdown:hover .dropdown-menu {
        display: inherit;
    }

    .nav-tabs .dropdown-menu,
    .nav-pills .dropdown-menu,
    .navbar .dropdown-menu {
        margin-top: 0;
    }

    .navbar .sub-menu:before {
        border-bottom: 7px solid transparent;
        border-left: none;
        border-right: 7px solid rgba(0, 0, 0, 0.2);
        border-top: 7px solid transparent;
        left: -7px;
        top: 10px;
    }

    .navbar .sub-menu:after {
        border-top: 6px solid transparent;
        border-left: none;
        border-right: 6px solid #fff;
        border-bottom: 6px solid transparent;
        left: 10px;
        top: 11px;
        left: -6px;
    }
</style>

<div id="home" class="banner about-banner page-breadcrumb">
    <div class="banner-info">
        <!--navigation-->
        <div class="navbar navbar-fixed-top top-nav">
            <nav>
                <div class="container">
                    <div class="navbar-header logo">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1><a href="@Url.Action("Index","Home")"><img src="~/Image/11112.png" /></a></h1>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div style="padding-right: 0px;" class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-right">

                            <li style="margin-right: 0px; margin-left: 0px; ">
                                <a href="@Url.Action("Index","Home")" class="link-kumya"><span data-letters="Главная">Главная</span></a>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;" class="dropdown">
                                <a data-toggle="dropdown" class="link-kumya dropdown-toggle"><span data-letters="О нас">О нас<b class="caret"></b></span></a>
                                <ul style="border-radius: 0px;" class="dropdown-menu" id="menu1">
                                    <li><a href="@Url.Action("About","About")">О нас</a></li>
                                    <li class="divider"></li>
                                    <li><a href="@Url.Action("Licenses","About")">Лицензии</a></li>
                                </ul>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;" class="dropdown">
                                <a data-toggle="dropdown" class="dropdown-toggle link-kumya active"><span data-letters="Услуги">Услуги<b class="caret"></b></span></a>
                                <ul style="border-radius: 0px;" class="dropdown-menu" id="menu2">
                                    <li>
                                        <a href="@Url.Action("Geodetic","Services")">Геодезические работы</a>
                                        <ul style="border-radius: 0px; width: 222px;" class="dropdown-menu sub-menu">
                                            <li><a href="@Url.Action("CaptureM","Geodetics")">Съемка М 1:500 и др.</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("ExecutiveShooting","Geodetics")">Исполнительные съемки</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("GeideticsWorks","Geodetics")">Геодезические работы по инвентаризации и отводу земельных участков юр. и физ. лиц</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("TransferToNature","Geodetics")">Вынос в натуру границ земельных участков</a></li>
                                        </ul>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="@Url.Action("LandManagement","Services")">Землеустроительные работы</a>
                                        <ul style="border-radius: 0px; width: 222px;" class="dropdown-menu sub-menu">
                                            <li><a href="@Url.Action("SectionUnion","LandManagements")">Раздел / Объединение земельных участков</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("AllocationLand", "LandManagements")">Разработка проекта отвода земельного участка</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("PreparationDocumentationLandPlot","LandManagements")">Подготовка документации для оформления договора аренды на земельный участок</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("PreparationDocumentationLandPrivatization","LandManagements")">Подготовка технической документации для приватизации земельного участкав</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("AppointmenCadastralNumber","LandManagements")">Присвоение кадастрового номера</a></li>
                                        </ul>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="@Url.Action("Evaluation","Services")">Оценочные работы</a>
                                        <ul style="border-radius: 0px; width: 222px;" class="dropdown-menu sub-menu">
                                            <li><a href="@Url.Action("EstimationLand","Evaluations")">Оценка земельных участков</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("PropertyValuation","Evaluations")">Оценка недвижимости</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("EvaluationEquipment","Evaluations")">Оценка оборудования</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("EvaluationCars","Evaluations")">Оценка автомобилей</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;" class="dropdown">
                                <a data-toggle="dropdown" class="link-kumya dropdown-toggle"><span data-letters="Новости">Новости<b class="caret"></b></span></a>
                                <ul style="border-radius: 0px;" class="dropdown-menu" id="menu3">
                                    <li><a href="@Url.Action("New", "New")">Новости</a></li>
                                    <li class="divider"></li>
                                    <li><a href="@Url.Action("Articles", "New")">Статьи</a></li>
                                </ul>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;" class="dropdown">
                                <a data-toggle="dropdown" class="link-kumya dropdown-toggle"><span data-letters="Документы">Документы<b class="caret"></b></span></a>
                                <ul style="border-radius: 0px;" class="dropdown-menu" id="menu4">
                                    <li><a href=@Url.Action("Codex", "Documents")>Кодексы</a></li>
                                    <li class="divider"></li>
                                    <li><a href=@Url.Action("Lex", "Documents")>Законы</a></li>
                                    <li class="divider"></li>
                                    <li><a href=@Url.Action("Resolutions", "Documents")>Постановления Кабинета Министров</a></li>
                                </ul>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;">
                                <a href="@Url.Action("Contact","Home")" class="link-kumya">
                                    <span data-letters="Контакты">Контакты</span>
                                </a>
                            </li>
                        </ul>
                        <div class="clearfix"> </div>
                    </div>
                </div>
            </nav>
        </div>

        <!--//navigation-->
        <div class="banner-text">
            <h2 style="font-family: 'Roboto Condensed', sans-serif;">Услуги</h2>
        </div>
    </div>
</div>

<div style="margin-bottom: 0px;" class="container body-content">
    <div class="row">
        <div class="col-sm-12" style="margin-top: 100px;margin-bottom: 0px;">
            <p class="textLage">Разработка проекта отвода земельного участка</p>
            <br />
            <br />
        </div>
    </div>
</div>


<div style="padding-top: 0px; padding-bottom: 50px;" class="welcome">
    <div style="padding-top: 0px;" class="container body-content">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
                <img style="width: 100%;" src="~/Image/LandManagement/img_art_2-min.jpg">
            </div>
            <div class="clearfix">
            </div>
            <div class="col-sm-12" style="padding-top: 25px; padding-bottom: 25px; ">
                <p style="font-family: 'Roboto Condensed', sans-serif; font-size: 18px;">
                    Разработка и согласование проектов землеустройства считается самым сложным, самым дорогим и самым трудоемким видом работ в землеустройстве.
                    Проект отведения земельного участка разрабатывается на основании:<br />
                </p>
                <ul style="list-style-type: circle; padding-left: 35px;">
                    <li><p class="textDisProduct"> решение органа местного самоуправления, к полномочиям, которого принадлежит предоставление в пользование или передача в собственность земельных участков;</li>
                    <li><p class="textDisProduct"> заключенных договоров между землевладельцами и землепользователями и разработчиком проекта отведения земельного участка;</li>
                    <li><p class="textDisProduct"> судебного решения.</li>
                </ul>
                <p style="font-family: 'Roboto Condensed', sans-serif; font-size: 18px;">
                    <span style="font-weight: bold;">Документы необходимые для разработки проекта из землеустройства относительно отведения земельного участка:</span>
                </p>
                
                <ul style="list-style-type: circle; padding-left: 35px;">
                    <li><p class="textDisProduct"> оригинал решения органа местного самоуправления, к полномочиям которого принадлежит предоставление в пользование или передача в собственность земельных участков;</li>
                    <li><p class="textDisProduct"> выкопирование из генерального плана или проекта формирования пределов, и тому подобное (желательно);</li>
                    <li><p class="textDisProduct"> копия материалов предыдущего согласования (если такие были);</li>
                    <li><p class="textDisProduct"> копии паспортных данных и идентификационного кода (физические лица);</li>
                    <li><p class="textDisProduct"> нотариально заверенная копия свидетельства о регистрации, уставу, копия свидетельства об уплате налогов, копия справки из единственного государственного реестра предприятий и организаций.</li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

biznes/Views/LandManagements/PreparationDocumentationLandPlot.cshtml
@{
    ViewBag.Title = "Подготовка документации для оформления договора аренды на земельный участок";
}



<style>
    .sidebar-nav {
        padding: 9px 0;
    }

    .dropdown-menu .sub-menu {
        left: 100%;
        position: absolute;
        top: 0;
        visibility: hidden;
        margin-top: -1px;
    }

    .dropdown-menu li:hover .sub-menu {
        visibility: visible;
    }

    .dropdown:hover .dropdown-menu {
        display: inherit;
    }

    .nav-tabs .dropdown-menu,
    .nav-pills .dropdown-menu,
    .navbar .dropdown-menu {
        margin-top: 0;
    }

    .navbar .sub-menu:before {
        border-bottom: 7px solid transparent;
        border-left: none;
        border-right: 7px solid rgba(0, 0, 0, 0.2);
        border-top: 7px solid transparent;
        left: -7px;
        top: 10px;
    }

    .navbar .sub-menu:after {
        border-top: 6px solid transparent;
        border-left: none;
        border-right: 6px solid #fff;
        border-bottom: 6px solid transparent;
        left: 10px;
        top: 11px;
        left: -6px;
    }
</style>

<div id="home" class="banner about-banner page-breadcrumb">
    <div class="banner-info">
        <!--navigation-->
        <div class="navbar navbar-fixed-top top-nav">
            <nav>
                <div class="container">
                    <div class="navbar-header logo">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1><a href="@Url.Action("Index","Home")"><img src="~/Image/11112.png" /></a></h1>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div style="padding-right: 0px;" class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-right">

                            <li style="margin-right: 0px; margin-left: 0px; ">
                                <a href="@Url.Action("Index","Home")" class="link-kumya"><span data-letters="Главная">Главная</span></a>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;" class="dropdown">
                                <a data-toggle="dropdown" class="link-kumya dropdown-toggle"><span data-letters="О нас">О нас<b class="caret"></b></span></a>
                                <ul style="border-radius: 0px;" class="dropdown-menu" id="menu1">
                                    <li><a href="@Url.Action("About","About")">О нас</a></li>
                                    <li class="divider"></li>
                                    <li><a href="@Url.Action("Licenses","About")">Лицензии</a></li>
                                </ul>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;" class="dropdown">
                                <a data-toggle="dropdown" class="dropdown-toggle link-kumya active"><span data-letters="Услуги">Услуги<b class="caret"></b></span></a>
                                <ul style="border-radius: 0px;" class="dropdown-menu" id="menu2">
                                    <li>
                                        <a href="@Url.Action("Geodetic","Services")">Геодезические работы</a>
                                        <ul style="border-radius: 0px; width: 222px;" class="dropdown-menu sub-menu">
                                            <li><a href="@Url.Action("CaptureM","Geodetics")">Съемка М 1:500 и др.</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("ExecutiveShooting","Geodetics")">Исполнительные съемки</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("GeideticsWorks","Geodetics")">Геодезические работы по инвентаризации и отводу земельных участков юр. и физ. лиц</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("TransferToNature","Geodetics")">Вынос в натуру границ земельных участков</a></li>
                                        </ul>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="@Url.Action("LandManagement","Services")">Землеустроительные работы</a>
                                        <ul style="border-radius: 0px; width: 222px;" class="dropdown-menu sub-menu">
                                            <li><a href="@Url.Action("SectionUnion","LandManagements")">Раздел / Объединение земельных участков</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("AllocationLand", "LandManagements")">Разработка проекта отвода земельного участка</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("PreparationDocumentationLandPlot","LandManagements")">Подготовка документации для оформления договора аренды на земельный участок</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("PreparationDocumentationLandPrivatization","LandManagements")">Подготовка технической документации для приватизации земельного участкав</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("AppointmenCadastralNumber","LandManagements")">Присвоение кадастрового номера</a></li>
                                        </ul>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="@Url.Action("Evaluation","Services")">Оценочные работы</a>
                                        <ul style="border-radius: 0px; width: 222px;" class="dropdown-menu sub-menu">
                                            <li><a href="@Url.Action("EstimationLand","Evaluations")">Оценка земельных участков</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("PropertyValuation","Evaluations")">Оценка недвижимости</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("EvaluationEquipment","Evaluations")">Оценка оборудования</a></li>
                                            <li class="divider"></li>
                                            <li><a href="@Url.Action("EvaluationCars","Evaluations")">Оценка автомобилей</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;" class="dropdown">
                                <a data-toggle="dropdown" class="link-kumya dropdown-toggle"><span data-letters="Новости">Новости<b class="caret"></b></span></a>
                                <ul style="border-radius: 0px;" class="dropdown-menu" id="menu3">
                                    <li><a href="@Url.Action("New", "New")">Новости</a></li>
                                    <li class="divider"></li>
                                    <li><a href="@Url.Action("Articles", "New")">Статьи</a></li>
                                </ul>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;" class="dropdown">
                                <a data-toggle="dropdown" class="link-kumya dropdown-toggle"><span data-letters="Документы">Документы<b class="caret"></b></span></a>
                                <ul style="border-radius: 0px;" class="dropdown-menu" id="menu4">
                                    <li><a href=@Url.Action("Codex", "Documents")>Кодексы</a></li>
                                    <li class="divider"></li>
                                    <li><a href=@Url.Action("Lex", "Documents")>Законы</a></li>
                                    <li class="divider"></li>
                                    <li><a href=@Url.Action("Resolutions", "Documents")>Постановления Кабинета Министров</a></li>
                                </ul>
                            </li>

                            <li style="margin-right: 0px; margin-left: 0px;">
                                <a href="@Url.Action("Contact","Home")" class="link-kumya">
                                    <span data-letters="Контакты">Контакты</span>
                                </a>
                            </li>
                        </ul>
                        <div class="clearfix"> </div>
                    </div>
                </div>
            </nav>
        </div>

        <!--//navigation-->
        <div class="banner-text">
            <h2 style="font-family: 'Roboto Condensed', sans-serif;">Услуги</h2>
        </div>
    </div>
</div>

<div style="margin-bottom: 0px;" class="container body-content">
    <div class="row">
        <div class="col-sm-12" style="margin-top: 100px;margin-bottom: 0px;">
            <p class="textLage">Подготовка документации для оформления договора аренды на земельный участок</p>
            <br />
            <br />
        </div>
    </div>
</div>


<div style="padding-top: 0px; padding-bottom: 50px;" class="welcome">
    <div style="padding-top: 0px;" class="container body-content">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
                <img style="width: 100%;" src="~/Image/LandManagement/54016-300x199-e1481179074939-min.jpg">
            </div>
            <div class="clearfix">
            </div>
            <div class="col-sm-12" style="padding-top: 25px; padding-bottom: 25px; ">
                <p style="font-family: 'Roboto Condensed', sans-serif; font-size: 18px;">
                    Становясь арендатором, Вы берете на себя ряд обязательств, среди которых — <span style="font-weight: bold;">вовремя оформлять продление договора аренды земельного участка (земли).</span> 
                    Однако продление срока действия договора аренды без смены границ и целевого назначения земли является и Вашим преимущественным правом. 
                    Осуществлять данную процедуру арендатору необходимо по окончании срока, на который договор был заключен. Кроме того, не позднее чем за месяц до окончания 
                    Договора необходимо проинформировать об этом арендодателя.<br /><br />
                </p>
                <p style="font-family: 'Roboto Condensed', sans-serif; font-size: 18px;">
                    Техническая документация для последующего оформления договора аренды земельного участка разрабатывается на основании:
                </p>
                <ul style="list-style-type: circle; padding-left: 35px;">
                    <li><p class="textDisProduct"> Техническая документация для последующего оформления договора аренды земельного участка разрабатывается на основании:</li>
                </ul>
                <p style="font-family: 'Roboto Condensed', sans-serif; font-size: 18px;">
                    Документы необходимые для разработки технической документации:
                </p>

                <ul style="list-style-type: circle; padding-left: 35px;">
                    <li><p class="textDisProduct"> оригинал решения органа местного самоуправления, к полномочиям которого принадлежит предоставление в пользование или передача в собственность земельных участков;</li>
                    <li><p class="textDisProduct"> выкопирование из генерального плана или проекта формирования пределов, и тому подобное (желательно);</li>
                    <li><p class="textDisProduct"> копия материалов предыдущего согласования (если такие были);</li>
                    <li><p class="textDisProduct"> копии паспортных данных и идентификационного кода (физические лица);</li>
                    <li><p class="textDisProduct"> нотариально заверенная копия свидетельства о регистрации, уставу, копия свидетельства об уплате налогов, копия справки из единственного государственного реестра предприятий и организаций.</li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>